name: willingly
description: Hemen hesabını oluşturarak yardım etmeye başlayabilirsin.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.0.1
  line_icons: ^0.2.0
  url_launcher: ^3.0.2
  http: ^0.12.0+2
  rflutter_alert: ^1.0.3
  google_maps_flutter: ^0.5.11
  fluttertoast: ^3.1.2
  animated_stream_list: ^0.0.5
  shared_preferences: ^0.5.3+4
  percent_indicator: "^2.1.1"
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/blank-profile-picture.png
   - assets/images/man1.jpg
   - assets/images/man2.jpg
   - assets/images/man3.jpg
   - assets/images/man4.jpg
   - assets/images/man5.jpg
   - assets/images/woman1.jpg
   - assets/images/woman2.jpg
   - assets/images/woman3.jpg
   - assets/images/woman4.jpg
   - assets/images/woman5.jpg
   - assets/images/home_page.png
   - assets/images/logo.png
   - assets/images/empty.png
   - assets/images/post_banner.jpg
   - assets/images/loading.gif
   - assets/images/willingly.png

  fonts:
   - family: Barlow
     fonts:
       - asset: assets/fonts/Barlow-Regular.ttf
       - asset: assets/fonts/Barlow-SemiBold.ttf
         weight: 400
       - asset: assets/fonts/Barlow-Bold.ttf
         weight: 700
   - family: Quicksand
     fonts:
       - asset: assets/fonts/Quicksand-Regular.ttf
       - asset: assets/fonts/Quicksand-Medium.ttf
       - asset: assets/fonts/Quicksand-SemiBold.ttf
       - asset: assets/fonts/Quicksand-Bold.ttf